# Generated by Django 4.2.21 on 2025-05-31 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('service_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=158, null=True)),
                ('delivery_remarks', models.CharField(blank=True, max_length=158, null=True)),
                ('estimated_price', models.IntegerField(blank=True, null=True)),
                ('actual_price', models.IntegerField(blank=True, null=True)),
                ('receiving_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_receivings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
