# Generated by Django 4.2.21 on 2025-05-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='delivery_remarks',
            field=models.CharField(default='no', max_length=158),
            preserve_default=False,
        ),
    ]
