# Generated by Django 4.2.21 on 2025-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_receiving_delivery_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='delivery_remarks',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='estimated_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='receiving_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='remarks',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
