# Generated by Django 5.0.1 on 2025-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_customer_receiving_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='delivery_image',
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='receiving_image',
        ),
        migrations.AlterField(
            model_name='receiving',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
