# Generated by Django 4.2.21 on 2025-05-31 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karate', models.CharField(blank=True, max_length=158, null=True)),
                ('color', models.CharField(blank=True, max_length=158, null=True)),
                ('input_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('output_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('machine_wastage', models.CharField(blank=True, max_length=158, null=True)),
                ('production_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Karate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karate', models.CharField(blank=True, max_length=158, null=True)),
                ('color', models.CharField(blank=True, max_length=158, null=True)),
                ('casting_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.CharField(blank=True, max_length=158, null=True)),
                ('converted24k', models.CharField(blank=True, max_length=158, null=True)),
                ('wastage_percentage', models.CharField(blank=True, max_length=158, null=True)),
                ('wastage_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('total_weight24k', models.CharField(blank=True, max_length=158, null=True)),
                ('gold_received', models.CharField(blank=True, max_length=158, null=True)),
                ('service_charges_rate', models.CharField(blank=True, max_length=158, null=True)),
                ('service_charges_amount', models.CharField(blank=True, max_length=158, null=True)),
                ('cash_received', models.CharField(blank=True, max_length=158, null=True)),
                ('remarks', models.CharField(blank=True, max_length=158, null=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_casting', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('flask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casting.flask')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_casting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
