# Generated by Django 4.2.21 on 2025-05-27 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karate', models.CharField(blank=True, max_length=158, null=True)),
                ('color', models.CharField(blank=True, max_length=158, null=True)),
                ('input_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('output_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('machine_wastage', models.CharField(blank=True, max_length=158, null=True)),
                ('production_weight', models.CharField(blank=True, max_length=158, null=True)),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='casting',
            name='cash_received',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='converted24k',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='gold_received',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='remarks',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='service_charges_amount',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='service_charges_rate',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='total_weight24k',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='wastage_percentage',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='wastage_weight',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='weight',
            field=models.CharField(blank=True, max_length=158, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='flask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casting.flask'),
        ),
    ]
