# Generated by Django 4.2.21 on 2025-05-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0002_flask_casting_cash_received_casting_converted24k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casting',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
